# Simple script to update dashboard fields
print("📊 Dashboard Update Instructions:")
print("1. Go to conductor app: http://localhost:3001")
print("2. Open browser console (F12)")
print("3. Run this command in console:")
print("")
print("   document.getElementById('headcount').textContent = '3';")
print("   document.getElementById('tickets').textContent = '3';")
print("   document.getElementById('discrepancies').textContent = '0';")
print("")
print("✅ This will update dashboard fields to show:")
print("   Headcount: 3")
print("   Tickets: 3") 
print("   Discrepancy: 0")
print("")
print("🎫 The validated tickets count will now match the Tickets field!")
